blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/amnweb/yasb/discussions
    about: Please ask and answer questions here.
  - name: Discord
    url: https://discord.com/invite/qkeunvBFgX
    about: Join our Discord server to chat with the community.